### ISSUE TITLE
Some feature recommendation

### ISSUE THREAD

**Issue by RishabhRD** [xeluxee/competitest.nvim#24]
Hi! First of all, thanks for the great plugin. I started using your plugin few days back and I am loving it.

There are some features that I would love to see personally. It may or may not be the goal of project.

- Split window for adding test cases
I am actually really good with split windows. Because moving from one window to another window just works seamlessly in split windows. I am kind of person who uses default vim bindings like `<C-w>h` and `<C-w>l` for moving between windows. Some custom keybindings annoy me. And these bindings doesn't work accurately for popup window.
- Closing with autocmds
If I close a window (with :q) for test case editor or runner, it should close all the related windows. Maybe autocmds can be used here. Then, special keybinding for closing the window would not be needed.
- Saving with autocmds
Saving any testcase is simple as saving file I feel. Because at last testcase editing is just editing a file. Maybe we can change buffer name for intuitiveness. So, this would remove any keybinding needed for saving the testcase. If something extra is needed, meybe BufWritePre or BufWritePost autocmds can be used.

These are basically just suggestions to enable me to use competitest buffers like normal buffers and nothing special.

If these are aligned with project goal and you need some sort of help in implementing these, I can definitely help you in these.

Thanks,
Rishabh Dwivedi

**Comment by xeluxee** [comment]
> First of all, thanks for the great plugin. I started using your plugin few days back and I am loving it.

I'm glad to hear that

> I am actually really good with split windows. Because moving from one window to another window just works seamlessly in split windows. I am kind of person who uses default vim bindings like <C-w>h and <C-w>l for moving between windows. Some custom keybindings annoy me. And these bindings doesn't work accurately for popup window.

With default configuration you can press `<C-h>` and `<C-l>` to jump between input and output windows. You can change these keybindings to `<C-w>h` and `<C-w>l` configuring `editor_ui.normal_mode_mappings.switch_window` (see [configuration](https://github.com/xeluxee/competitest.nvim#full-configuration))

> If I close a window (with :q) for test case editor or runner, it should close all the related windows. Maybe autocmds can be used here. Then, special keybinding for closing the window would not be needed.

Instead of using `:q` you should just press `q` in normal mode to close all the windows. This mappings is configurable too: see `editor_ui.cancel` and `runner_ui.mappings.close`
Nevertheless I could use an autocommand to close all the windows when closing one

> Saving any testcase is simple as saving file I feel. Because at last testcase editing is just editing a file.

Unluckily no, because testcases can be stored in a [single msgpack-encoded file](https://github.com/xeluxee/competitest.nvim#storing-testcases-in-a-single-file), not only in text files

**Comment by RishabhRD** [comment]
> With default configuration you can press <C-h> and <C-l> to jump between input and output windows. You can change these keybindings to <C-w>h and <C-w>l configuring editor_ui.normal_mode_mappings.switch_window (see [configuration](https://github.com/xeluxee/competitest.nvim#full-configuration))
Yeah, I agree with this, I just needed to add `<C-w><C-h>` and `<C-w><C-l>`, just in case I was pressing Ctrl and h/l simultaneously :sweat_smile: . And with this, I think need for split mode is not there.

For other features, I have opened a PR #25 . We can discuss, if these are aligned to project goals.

**Comment by xeluxee** [comment]
Closing with #25
